dist: trusty
os: linux
language: python
python:
    - "3.6"

branches:
    only:
        - master

env:
    global:
        - secure: "ti6s8wrDkhnOcrIRFtcrKSmaRqXk9VBi6aZNU5fGA6RurkbEknRsGNH4rTf1mHoAPcJV0DRYyLKlnOn6HJEhLI/JN/O1G3xA7TO9v4u8lhqnws3uh8WlQDmkpKFqTd1SAjTpNAEGXIOqljknz1hGsMpJN+KEfLz10JoanDKhj68gLaNPHput7rlwr2Fs5ik6MjuUPDw3cK9QfCMljIA10RiExfy/70NDiIJpXcRDv0BHxDoS3qREHhZ2EJgCkWiOQuG2AIzEeQMRk5la48SkpMs2w9/7/lBWk99imI7av92iy4y71DFJJ++EZCw6OGHefXE6+ZZ9748XRBJ5hzhBSxznYC6SAI6KtkPXqv5WsnS5YHrbDFzloyYVxH88DEZ3dTCLK/48T+7Ab00FOZCVVUSEvuDvM6l5/fvHl63fRzVPcJ/PknD+NNMOOTAhecX3CFYyKvd0noPpvCvawUUPfiWQjtXA9SvEPuQKBX1Z5qQVm6AjedIW9Rwjem7rQC8SD3XZFnLFs4f7T21yxQTLwdw4yAWI+OUK7BStWZWo1sjjPcf8CeqpD8B8KgRtBI4Bp2REOtCREH4+i8aZlTXAObPE73Efda9/iW0f1W51leXtVDw5AFyAjW1aab7mwrjxsFQ3PbgFcZ5wGTdLui4LCxAH96QORJp68RlYbazowyc="

install:
    - |
      set -xe
      pip install sphinx sphinxcontrib.autoprogram doctr
      python setup.py develop

script:
    - |
      set -xe
      # Build docs
      pushd docs
      make html
      popd
      # Maybe deploy documentation
      if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
          doctr deploy . --built-docs docs/build/html/
      fi

notifications:
  email: false
